### ISSUE TITLE
建议检测node最低版本

### ISSUE THREAD

**Issue by hzexe** [yioMe/nodejs_wx_aipay_api#12]
linux发行版上node的版本都比较老，而npx又可以通过npm安装，踩坑了

**Comment by yioMe** [comment]
package.json 文件里有说明最低nodejs版本。

**Comment by yioMe** [comment]
你好，提供前台代码的，vuejs开发的。

**Comment by hzexe** [comment]
我环境是这样子的:
 Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-109-generic x86_64)
root@v6:/var/www/pay# npx -v
6.9.0
root@v6:/var/www/pay# node -v
v11.12.0
root@v6:/var/www/pay#  npm -v
6.9.0
root@v6:/var/www/pay#

---------------------
改了配置之后，按教程走到
```bash
root@v6:/var/www/pay# npx sequelize db:migrate

Sequelize CLI [Node: 11.12.0, CLI: 5.4.0, ORM: 4.43.0]


ERROR: Cannot find "/var/www/pay/config/config.json". Have you run "sequelize init"?

root@v6:/var/www/pay# ls config
config.default.js  plugin.js

```

需要帮助,我不知道是哪块的环境出问题。我在win下很轻松就部属上，而到生产环境，就跑偏了

**Comment by hzexe** [comment]
把源码删除后，重新clone修改后跑通了……）：
