### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by BarryYang1** [yioMe/nodejs_wx_aipay_api#14]
`
C:\Users\Administrator\Desktop\nodejs_wx_aipay_api-master>npm start

> ali_wx_pay@1.0.0 start C:\Users\Administrator\Desktop\nodejs_wx_aipay_api-mast
er
> egg-scripts start --daemon --title=egg-server-ali_wx_pay

[egg-scripts] Starting egg application at C:\Users\Administrator\Desktop\nodejs_
wx_aipay_api-master
[egg-scripts] Run node C:\Users\Administrator\Desktop\nodejs_wx_aipay_api-master
\node_modules\egg-scripts\lib\start-cluster {"title":"egg-server-ali_wx_pay","ba
seDir":"C:\\Users\\Administrator\\Desktop\\nodejs_wx_aipay_api-master","framewor
k":"C:\\Users\\Administrator\\Desktop\\nodejs_wx_aipay_api-master\\node_modules\
\egg"} --title=egg-server-ali_wx_pay
[egg-scripts] Save log file to C:\Users\Administrator\logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] Wait Start: 6...
[egg-scripts] tail -n 100 C:\Users\Administrator\logs\master-stderr.log
[egg-scripts] ignore tail error: Error: spawn tail ENOENT
[egg-scripts] Start got error, see C:\Users\Administrator\logs\master-stderr.log

[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ali_wx_pay@1.0.0 start: `egg-scripts start --daemon --title=egg-server-
ali_wx_pay`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ali_wx_pay@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Tools\nodejs\node_cache\_logs\2019-04-02T08_00_40_258Z-debug.log
`

**Comment by yioMe** [comment]
你好，请勿重复启动你的服务，即你已经执行过npm start 如果你想停止你的服务请执行 npm stop。 注：要在你的项目根目录里执行上述命令。
