### ISSUE TITLE
安卓客户端没有推送消息到服务器？如何解决

### ISSUE THREAD

**Issue by dreamfit** [yioMe/nodejs_wx_aipay_api#15]
你好：

       我安卓客户端已允许读取通知权限，并且配置正确验证通过（http://服务器地址/addons/pay/ ）。
但是，

      我扫码支付宝支付后，订单管理没有更新成已支付。倒是看见订单变成了，已过期。

     找日志，似乎安卓没有推送支付消息到服务器。请问如何解决

**Comment by yioMe** [comment]
你好，订单有效期为5分钟，失效后支付的订单不会处理订单状态也不会回调通知，请在配置中修改订单有效期，请通过购买客户端邮箱联系a@yio.me获取更多支持，谢谢！
