### ISSUE TITLE
没有数据库玩个屌

### ISSUE THREAD

**Issue by 1144744046** [yioMe/nodejs_wx_aipay_api#16]
没有数据库玩个屌

**Comment by yioMe** [comment]
您好https://github.com/yioMe/nodejs_wx_aipay_api/#%E6%96%87%E6%9C%AC%E6%95%99%E7%A8%8B
文本教程第四步是创建数据表的，当然数据库需要您手动创建程序并没有创建收据库的能力，格式utf-8；
