### ISSUE TITLE
兄dei，支付宝唤起好像有点问题

### ISSUE THREAD

**Issue by zhkumsg** [yioMe/nodejs_wx_aipay_api#17]
我试了一下，不设金额的支付宝收款码解析后，可以正常唤起支付宝，
但是对于设置了金额的支付宝收款码，唤起支付宝后会提示“暂不支持此种方式请在支付宝里打开”

**Comment by yioMe** [comment]
你好
请更新您的支付宝客户端，如果您的支付宝是旧版本请按照 app/controller/order.js 第127行根据注释使用旧的appid

**Comment by yioMe** [comment]
支付宝版本(10.1.60)及以上称为“新版本”，以下称为“旧版本”。
