### ISSUE TITLE
最新版本支付宝不能唤醒

### ISSUE THREAD

**Issue by xcation** [yioMe/nodejs_wx_aipay_api#23]
不能唤醒。

**Comment by yioMe** [comment]
唤醒演示链接: https://pan.baidu.com/s/1YQRU96GvDRDJhM00wqTYbg 提取码: jt95

**Comment by xcation** [comment]
老铁，我发 地址给你 alipays://platformapi/startapp?appId=20000691&url=http%3A%2F%2Falipay.tylbd.top%3A7001%2Falipay.html%3Fu%3D2088531192984820%26a%3D0.03

**Comment by xcation** [comment]
PC 扫码可以的，我用了后面的  url  生成二维码，电脑上扫码，手机截屏扫码不行，提示风险
