### ISSUE TITLE
唤起

### ISSUE THREAD

**Issue by xcation** [yioMe/nodejs_wx_aipay_api#24]
老铁，我发 地址给你 alipays://platformapi/startapp?appId=20000691&url=http%3A%2F%2Falipay.tylbd.top%3A7001%2Falipay.html%3Fu%3D2088531192984820%26a%3D0.03

pc 扫码可以，手机截图扫码 后面的地址 不行

**Comment by yioMe** [comment]
你好，测试扫码是可以识别的，测试地址 https://cli.im/text?2feafb3c954e7b56687581916b6524b1

**Comment by xcation** [comment]
手机截屏，扫码不行，

**Comment by xcation** [comment]
H5 也不行

**Comment by xcation** [comment]
是不是 风控了

**Comment by yioMe** [comment]
我使用我的支付宝是可以扫描的，请确定你的支付宝收款账号和付款账号不是同一个，否则不排除被风控的可能性~

**Comment by yioMe** [comment]
这种问题不是程序的问题，这个iss将会被删除~
