### ISSUE TITLE
config.default.js和database的config.js有什么区别

### ISSUE THREAD

**Issue by JankingWon** [yioMe/nodejs_wx_aipay_api#25]
http://地址/api/update
为404

上传文件也上传不上去

**Comment by yioMe** [comment]
config.default.js是网站配置信息，database的config.js是建表结构是需要的，后面就没有什么用处了，上传不上的原因 1.收款二维码是定额的二维码不是你的微信二维码，二维码收款->设置金额->保存收款二维码（不能修改任何文字信息，否则会无法识别报404）;2.你的百度orc（文字识图）配置有误。3.你的数据库配置有误；

**Comment by JankingWon** [comment]
好的，感谢
