### ISSUE TITLE
为啥 我 npx sequelize db:migrate 总是报错

### ISSUE THREAD

**Issue by licao** [yioMe/nodejs_wx_aipay_api#4]
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13

怎么解决，找了好长时间了还是没解决

**Comment by licao** [comment]
错了，是这个错，TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number

**Comment by yioMe** [comment]
你是否修改表结构了?

**Comment by licao** [comment]
> 你是否修改表结构了?

没有动过，按照步骤来的，很奇怪

**Comment by licao** [comment]
错是因为 config.json 里的 password 类型必须为 字符串，

**Comment by yioMe** [comment]
嗯，那我关闭这个 is了
