### ISSUE TITLE
如果有人创建了一笔订单，但是有第三个人这个时候转账进来

### ISSUE THREAD

**Issue by llsy** [yioMe/nodejs_wx_aipay_api#6]
如果有人创建了一笔订单，但是有第三个人这个时候转账进来，
这笔费用会自动充值到第一个人的账户里面吗

**Comment by yioMe** [comment]
不会，因为不可能在同时创建同一金额的订单，会在原金额的基础上随机减免，单位0.01元。

**Comment by llsy** [comment]
@yioMe 
我指的是有一个第三方的人
例如小明扫码要给我付5块钱了，系统给他生成了5.01的订单了，但是实际他还没付款
然后小黄就是认识我，他知道我这个支付宝，直接给我转了5.01
刚好小黄转给我的时候小明在有效期内，这个时候是不是小明会直接充值成功

**Comment by yioMe** [comment]
小明会直接充值成功。
