### ISSUE TITLE
通过支付宝扫码后支付宝提示：收款方当日设置金额的收款次数已达上限

### ISSUE THREAD

**Issue by hzexe** [yioMe/nodejs_wx_aipay_api#7]
一天内貌似同一金额只能收10次？是这个锅的原因吗。是不是要把这10次的条件也加到查询的过滤里面

**Comment by yioMe** [comment]
你好，这个不是收款系统的限制，收款系统使用的金额二维码是可以循环使用的，提示这个的原因是官方限制每天的收款二维码生成的次数20次；你可以每天生成19张，然后传到收款系统即可循环使用。
