### ISSUE TITLE
db移植出错

### ISSUE THREAD

**Issue by zzxjl1** [yioMe/nodejs_wx_aipay_api#8]
Loaded configuration file "database/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
== 20190117132136-init-yio_qrcodes: migrating =======

ERROR: Unexpected token (

**Comment by yioMe** [comment]
检查你的数据库格式 字符集 utf8 排序规则 utf8_general_ci
